uint8 COMPRESS_ONCE = 1
uint8 COMPRESS_HOLD = 2
uint8 STOP = 3
uint8 FORCE_STOP = 4

uint8 command
float64 target_pressure
float64 cpm  16.0
float64 speed_rpm 1500.0
---
bool accepted
string message
---
float64 pressure
float64 percent_complete
