uint8 START = 1
uint8 START_IDLE = 2
uint8 STOP = 3
uint8 SAFE_STOP = 4

uint8 command
float64 target_pressure
float64 cpm  16.0
float64 speed_rpm 1500.0
---
bool accepted
string message
---
float64 pressure
float64 percent_complete
