# srv/BCompressorrCmd.srv
uint8 INVALID = 0
uint8 CONTROL_SV = 1
uint8 CONTROL_HEATER = 2

uint8 cmd

bool      enable        # CONTROL_SV / CONTROL_HEATER — energise the targeted device
uint8     index         # CONTROL_SV — index into CompressorTelemetry::sv[5]
float64   setpoint      # CONTROL_HEATER - gives a setpoint for heater
---
bool    success
string  message
